### ISSUE TITLE
Split readme in userguide and adminguide

### ISSUE THREAD

**Issue by vmiheer** [CHPC-UofU/spack-config#3]
It would be great to have seperation between userguide and adminguide than having single monolithing README.md

**Comment by mcuma** [comment]
Good idea, I will work on that.

**Comment by mcuma** [comment]
Miheer, please see https://github.com/CHPC-UofU/spack-config/blob/master/readme-user.md#basic-installation-workflow and let me know how it looks. Thanks.

**Comment by vmiheer** [comment]
This is awesome thank you!
